run:
  timeout: 3m
  go: "1.26"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
