exclude_patterns:
- '**/.*'
- '**/__pycache__'
- '**/node_modules'
- '**/target'
- '**/build/assets'
- '**/dist'
- '**/vendor/*.*/*'
- '**/vendor/*'
- '**/.cocoindex_code'
include_paths:
- /Users/jwalinshah/dotfiles
- /Users/jwalinshah/projects
include_patterns:
- '**/*.go'
- '**/*.py'
- '**/*.ts'
- '**/*.tsx'
- '**/*.swift'
- '**/*.sh'
- '**/*.bash'
- '**/*.md'
- '**/*.sql'
- '**/*.yaml'
- '**/*.yml'
- '**/*.toml'
- '**/*.json'
- '**/*.cpp'
- '**/*.c'
- '**/*.typ'
chunkers:
- ext: go
  module: tldr_chunker:chunk
- ext: py
  module: tldr_chunker:chunk
- ext: rs
  module: tldr_chunker:chunk
- ext: ts
  module: tldr_chunker:chunk
- ext: tsx
  module: tldr_chunker:chunk
- ext: js
  module: tldr_chunker:chunk
- ext: c
  module: tldr_chunker:chunk
- ext: cpp
  module: tldr_chunker:chunk
- ext: swift
  module: tldr_chunker:chunk
- ext: sh
  module: tldr_chunker:chunk
- ext: bash
  module: tldr_chunker:chunk
- ext: md
  module: tldr_chunker:chunk
- ext: sql
  module: tldr_chunker:chunk
- ext: yaml
  module: tldr_chunker:chunk
- ext: yml
  module: tldr_chunker:chunk
- ext: toml
  module: tldr_chunker:chunk
- ext: json
  module: tldr_chunker:chunk
- ext: typ
  module: tldr_chunker:chunk
